### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by redbear-ger** [hughbris/grav-theme-landed#1]
I'm going crazy... how do I fill the sidebar?
I know it's not nen issue actually, but after 1 hour trying ... =)

**Comment by redbear-ger** [comment]
ok... got it with demo content ;)

**Comment by hughbris** [comment]
LOL, I slept through that :) Glad to see this being used. Please log an issue if you find any problems or see improvements I could make.

You could also have just hacked/overridden the appropriate template with hardcoded content if that's palatable.

I really need to make theme blueprints so that this kind of change is more intuitive. In fact, I'm creating an issue for that right now :)
