### ISSUE TITLE
Incompatibility Grav 1.7: No |raw for content and assets

### ISSUE THREAD

**Issue by pamtbaau** [hughbris/grav-theme-landed#10]
Hi Hugh, Hope this finds you well...

Did some `grep`-ing on all themes and found this theme lacking the filter `|raw`, which will render the theme incompatible with Grav 1.7

You may want to take a look at:
- user/themes/landed/templates/partials/sections/intro.html.twig:   {{ page.content }}
- user/themes/landed/templates/partials/base.html.twig:                  {{ assets.css() }}
- user/themes/landed/templates/partials/base.html.twig:                  {{ assets.js() }}
- user/themes/landed/templates/partials/base.html.twig:                  {{ page.content }}
- user/themes/landed/templates/partials/base.html.twig:                  {{ assets.js('bottom') }}

**Comment by hughbris** [comment]
Thank you, I've been too busy and this is low on my list since I am not using the theme anywhere published.

Thank you for doing an audit of themes, it's necessary in my opinion. If you need to suspend this from the official theme repository until fixed I will not be offended, in fact I think that should happen!

**Comment by pamtbaau** [comment]
Out of curiosity: Did you publish both themes because you wanted to share them with the community, or because it is convenient to be able to use GPM in your own projects?

I'm asking this because I fear most themes/plugins have been published for own convenience. I suspect this is the reason so many themes/plugins have been abandoned. I would expect more vigilance of the owner with respect to responding to issues, upgraded etc. when the theme/plugin was released with the community in mind. What's you thinking?

By the way, do you have any thoughts to share on this [discussion](https://github.com/getgrav/grav/discussions/3490)?

**Comment by hughbris** [comment]
The first reason is only one of the reasons I published them.

Any convenience (GPM) is incidental and minimal. I use plenty of themes and plugins I have not put into the repository, as well as some private ones, and I use my forks of some plugins because my patches are not accepted.

I have strong feelings about Grav's trajectory but I stay out of Grav politics now because I seem to easily offend its maintainers and can't afford to have poor relations. Thanks for raising this stuff.

**Comment by pamtbaau** [comment]
Script finds the following:
- user/themes/landed/templates/partials/sections/intro.html.twig: {{ page.content }}

Here's the script for testing on content and assets output:
```
find user/themes/$1 -name "*.html.twig" \
-exec grep -PH \
'assets.(js|css)\(([^)]+)?\)\s*(?!(\|\s*raw\s*))}}|(?<!meta)\.content\s*(\|([^rm](?!raw|markdown))+?)?}}' \
{} \;
```

**Comment by hughbris** [comment]
Thank you for picking that up. When I have updated my demos, I will tag a new release.
